name: Pull request triggered

on: [pull_request]

jobs:
  dosomething:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: |
          echo "Will add code checks here in next challenge"
